"""empty message

Revision ID: 0427305b1329
Revises: 
Create Date: 2022-05-29 02:01:22.391841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0427305b1329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=254), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('editora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['editora_id'], ['editoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obras')
    op.drop_table('editoras')
    op.drop_table('autores')
    # ### end Alembic commands ###
