"""empty message

Revision ID: 78111341086d
Revises: 0427305b1329
Create Date: 2022-05-29 22:28:12.814053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78111341086d'
down_revision = '0427305b1329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'autores', ['nome'])
    op.create_unique_constraint(None, 'editoras', ['nome'])
    op.create_unique_constraint(None, 'obras', ['titulo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obras', type_='unique')
    op.drop_constraint(None, 'editoras', type_='unique')
    op.drop_constraint(None, 'autores', type_='unique')
    # ### end Alembic commands ###
